version: "3"

services:
  writer:
    build: writer/
    command: python -m home.main
    volumes:
      - ./common:/home/common/

  reader:
    build: reader/
    command: python -m home.main
    volumes:
      - ./common:/home/common/
    depends_on:
      - writer
